hide_download: true
hide_download_original: null
leftnav:
- identifier: 04e43244-9358-0cc1-7a35-74a2b6151c59
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: ae8b9f1b-d1b0-3d3c-4a3c-a558f8fe1141
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 28c9b314-7956-f446-de35-8163e082fd34
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: 801fa253-f5eb-de84-048e-e39c0b02cd11
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 40
- identifier: 725f2e04-cada-aedb-a6e0-9d255b409d98
  name: Assignments
  pageRef: /pages/assignments
  weight: 50
- identifier: 0c836ede-bced-5147-2ea8-e24a982889db
  name: Projects
  pageRef: /pages/projects
  weight: 60
